apiVersion: argoproj.io/v1alpha1
kind: hook
metadata:
  name: springdemoapp
  annotations:
    argocd.argoproj.io/hook: PostSync
spec:
  manifest: |
    apiVersion: argoproj.io/v1alpha1
    kind: Application
    metadata:
      name: springdemoapp
      namespace: default
    spec:
      project: default
      source:
        repoURL: https://github.com/rajshivaram/argocd-app-db.git
        path: dev/deployment.yaml
        targetRevision: HEAD
      destination:
        server: https://kubernetes.default.svc
        namespace: default
---
apiVersion: argoproj.io/v1alpha1
kind: hook
metadata:
  name: springdemoapp-service
  annotations:
    argocd.argoproj.io/hook: PostSync
spec:
  manifest: |
    apiVersion: argoproj.io/v1alpha1
    kind: Application
    metadata:
      name: install-service
      namespace: default
    spec:
      project: default
      source:
        repoURL: https://github.com/rajshivaram/argocd-app-db.git
        path: dev/service.yaml
        targetRevision: HEAD
      destination:
        server: https://kubernetes.default.svc
        namespace: default
