apiVersion: argoproj.io/v1alpha1
kind: hook
metadata:
  name: springdemo-postgres
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  manifest: |
    apiVersion: argoproj.io/v1alpha1
    kind: Application
    metadata:
      name: springdemo-postgres
      namespace: default
    spec:
      project: default
      source:
        repoURL: https://github.com/rajshivaram/argocd-app-db.git
        path: dev/postgres-claim.yaml
        targetRevision: HEAD
      destination:
        server: https://kubernetes.default.svc
        namespace: default
