apiVersion: argoproj.io/v1alpha1
kind: hook
metadata:
  name: install-database
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  manifest: |
    apiVersion: argoproj.io/v1alpha1
    kind: Application
    metadata:
      name: install-database
      namespace: default
    spec:
      project: default
      source:
        repoURL: <github_repo_url>
        path: argocd/claim.yaml
        targetRevision: HEAD
      destination:
        server: https://kubernetes.default.svc
        namespace: default
